language: r
cache: packages
latex: false

r_github_packages:
  - ropensci/testdat
  - willpearse/suppdata
  - willpearse/fulltext
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
