sudo: false
language: r
cache: packages
latex: false

addons:
  apt:
    packages:
      libmagick++-dev
     
after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: --no-build-vignettes --resave-data
r_check_args: --no-tests --no-build-vignettes

