sudo: false
language: r
cache: packages
latex: false

addons:
  apt:
    packages:
      libmagick++-dev

r_github_packages:
  - ropensci/testdat
  - ropensci/suppdata
  - r-lib/covr
      
after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
