sudo: false
language: r
latex: true

cache:
  - packages
      
after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: --no-build-vignettes --resave-data
r_check_args: --no-tests --no-build-vignettes --ignore-vignettes

